name: 'Build an Alfred Workflow [enhanced]'
description: 'Compile contents of a workflow dir to a ZIP file with extension .alfredworkflow'
author: 'com30n'
branding:
  icon: 'archive'
  color: 'yellow'
inputs:
  workflow_dir:
    description: 'Directory containing the sources of the workflow'
    required: false
    default: 'workflow'
  exclude_patterns:
    description: 'List of excluded files/directories'
    required: false
    default: ''
  template_files:
    description: 'List of comma separated paths to files that would be used to template your `info.plist` file. See README.md for an additional info'
    required: false
    default: ''
  custom_version:
    description: 'String that will override the workflow version'
    required: false
outputs:
  workflow_file:
    description: 'The name of the created .alfredworkflow file'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    CUSTOM_VERSION: ${{ inputs.custom_version }}
  args:
    - ${{ inputs.workflow_dir }}
    - ${{ inputs.exclude_patterns }}
    - ${{ inputs.template_files }}
